### ISSUE TITLE
Carthage fails to build ReSwiftRouter

### ISSUE THREAD

**Issue by leandromperez** [ReSwift/ReSwift-Router#103]
Hi,

I am trying to build ReSwiftRouter using carthage update --platform ios. 

Carthage fails to build ReSwiftRouter, here's the console log, and attached the actual log.

Probably this isn't a bug, but something I have missed...

Any thoughts?

[carthage.log](https://github.com/ReSwift/ReSwift-Router/files/2462328/carthage.log)

*** Building scheme "ReSwiftRouter-iOS" in ReSwiftRouter.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/leandro/Workspace/Personal/Movies/Movies\ ReSwift/Carthage/Checkouts/ReSwiftRouter/ReSwiftRouter.xcodeproj -scheme ReSwiftRouter-iOS -configuration Release -derivedDataPath /Users/leandro/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10A254a/ReSwiftRouter/0.6.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/20/m6g4v1c91x1dyk_t2dkqm67m0000gn/T/ReSwiftRouter SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/leandro/Workspace/Personal/Movies/Movies ReSwift/Carthage/Checkouts/ReSwiftRouter)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/20/m6g4v1c91x1dyk_t2dkqm67m0000gn/T/carthage-xcodebuild.VThy0u.log
[carthage.log](https://github.com/ReSwift/ReSwift-Router/files/2462320/carthage.log)

**Comment by jjgp** [comment]
Do you mind sharing your Cartfile? I'm guessing we need to rev the version of ReSwiftRouter. For example the following Cartfile will compile:

https://github.com/jjgp/ReddiX-iOS/blob/master/Cartfile

Carthage is likely pulling the last tagged version. I used "master" in the Cartfile above.

**Comment by leandromperez** [comment]
Thanks for your response, i'll take a look and see if using "master" does the trick.

**Cartfile**
github "ReactiveX/RxSwift" ~> 4.0
github "ReSwift/ReSwift"
github "ReSwift/ReSwiftRouter"
github "RxSwiftCommunity/RxSwiftExt"
github "Moya/Moya"

**Cartfile.Resolved**
github "Alamofire/Alamofire" "4.7.3"
github "Moya/Moya" "11.0.2"
github "ReSwift/ReSwift" "4.0.1"
github "ReSwift/ReSwiftRouter" "0.6.0"
github "ReactiveCocoa/ReactiveSwift" "3.1.0"
github "ReactiveX/RxSwift" "4.3.1"
github "RxSwiftCommunity/RxSwiftExt" "3.3.0"
github "antitypical/Result" "3.2.4"

**Comment by leandromperez** [comment]
That worked! thanks @jjgp

**Comment by jjgp** [comment]
great! when I have an issue opened to look at the versioning some more and will revisit this there.
