### ISSUE TITLE
Enums as RouteElementIdentifier

### ISSUE THREAD

**Issue by ciathyza** [ReSwift/ReSwift-Router#113]
Would it be possible (and make sense) to change the ReSwiftRouter code to use String enums for the RouteElementIdentifier instead of just string?

It would be much cleaner to use enums in the Routable callback methods instead of string. But I'm wondering how this could be changed so that a custom (project-defined) string enum can be used with the router.

Any ideas?

**Comment by DivineDominion** [comment]
RawRepresentable with String might be an option. Closing b/c inactive for so long
