### ISSUE TITLE
AddRouter case / TabBar how to implement... questions

### ISSUE THREAD

**Issue by UXDart** [ReSwift/ReSwift-Router#120]
Hello! two questions:
1) why there isn't a AddRouteAction()? if I just want to push a view, why I need to know the current route? seems like the most used use case of a router...I must be missing something...
2) how do you work with a TabBar, where each tabBarItem has it's own route?

Thanks!

note: I'm using a navigation controller on each tabbar item

**Comment by DivineDominion** [comment]
It sounds like you are looking for https://github.com/ReSwift/ReSwift-Router/pull/89, right?

There's a few tests for the reducer missing, I think, but otherwise it's a good start. With regard to #122, would you want to take over the implementation of #89's features in your own PR?
