### ISSUE TITLE
can I help?

### ISSUE THREAD

**Issue by UXDart** [ReSwift/ReSwift-Router#122]
what I want to write, but the question is if (not 100% sure but) you will include it into the package? what I want to do is a way to:
* push a new route into the actual route (simple thing)
* support for tabbar, auto save each route for each tabbar
* support for push a VC "with specificData" (not two calls)
* easy way to manage specificData for each route part inside a route
* and what I need, but I will need some guide here, is to allow the state to show the specificdata for the current VC... so on newState you can check the specificdata of that VC directly
* auto save/restore actual nav state (to disk)

what do you think?

**Comment by DivineDominion** [comment]
As far as I can tell, nobody is pushing an agenda for the Router, so your ideas might not conflict with anybody else's. I think your ideas are pretty cool! 

So, PRs are always welcome, but I would like to suggest you start with the least invasive changes to get us all up to speed again with the library during the PR reviews :)
