### ISSUE TITLE
Cannot use ReSwift-Router with ReSwift 6.x

### ISSUE THREAD

**Issue by blastar** [ReSwift/ReSwift-Router#128]
When using Swift Package Manager I cannot add ReSwift-Router when using newest ReSwift version 6.x because of wrong dependecy in Package.swift - upToNextMajor(from: "5.0.0")

**Comment by DivineDominion** [comment]
See #127

Would be great if you could submit a fix, pin to 6.1 and make some Swift updates. None of the ReSwift core team is currently using the Router package, I think

**Comment by BergQuester** [comment]
FWIW, this was fixed in https://github.com/ReSwift/ReSwift-Router/pull/129

**Comment by DivineDominion** [comment]
Thanks for the ping
