### ISSUE TITLE
SetRouteAction break separation of concerns

### ISSUE THREAD

**Issue by jschmid** [ReSwift/ReSwift-Router#15]
Requiring every view controller to know the whole application hierarchy breaks the separation of concerns. I am going to try to find a simple example to show what I mean. Again, this is heavily related to #3 and #4.

Say you are in the state (where each letter is a controller):

> A -> B -> C

And `C` wants to show something that is its child. It's easy for it to add a new controller to the list:

> A -> B -> C -> D

But now if `C` wants to show something that is out of its scope, like:

> A -> E -> F

`C` should only be able to send an `Action` saying "I want to show `F`", without having to know about the whole "breadcrumb" to get there.

I could create and action called `ShowF` and having a reducer that knows how to create the correct `Route`. However, this reducer will be forbidden to dispatch `SetRouteAction` since it is already inside a dispatch action of `ShowF`.

Does this make sense?

**Comment by jschmid** [comment]
Alright, I edited the issue text.

**Comment by Ben-G** [comment]
@jschmid Yes this makes sense! I definitely want to tackle setting relative routes. I presume once this router is further along, `SetRouteAction` will be rarely used, as there will be actions to set relative paths.

For now, you can implement your own action, e.g. `ShowF`. You actually don't need to call the `SetRouteAction`. 

One thing you could do for now, is not use the `NavigationReducer` and instead provide your own reducer that owns the current route in the state. It would be very easy to implement `ShowF` and `SetRoute` within your own reducer.

Luckily the Router doesn't rely on the `NavigationReducer` being used.

This example setup would change accordingly:

```
struct AppReducer: Reducer {
    func handleAction(action: Action, state: FakeAppState?) -> FakeAppState {
        return FakeAppState(
            navigationState: YourCustomNaivationReducer.handleAction(action, state: state?.navigationState)
        )
    }
}
```

And you could reuse the `NavigationReducer` implementation for your custom reducer and go from there!

Let me know if that works for you and thanks a lot for bringing up these issues!

**Comment by Ben-G** [comment]
@jschmid This definitely should be doable with the current router setup. Have you found a satisfying solution? :smiley:

**Comment by Ben-G** [comment]
Since this issue has gone stale, I'm going to close it for now! Let me know if something new comes up and I can re-open!
