### ISSUE TITLE
Help with SetRouteSpecificData

### ISSUE THREAD

**Issue by avdwerff** [ReSwift/ReSwift-Router#24]
I tried to play around with the new feature: SetRouteSpecificData , but somehow I can't get it working.
Basically when replacing a working SetRouteAction with SetRouteSpecificData, the route change is not performed... 

so for example:

store.dispatch(SetRouteAction(["root", "login", "dialog"]))

is working just fine, but:

store.dispatch(SetRouteSpecificData(route: ["root", "login", "dialog"], data: error))

not.

Did I miss something?

**Comment by Ben-G** [comment]
@avdwerff Setting the route specific data does by itself not trigger a route change. It only is used to store information for a route; you still need to call `SetRouteAction` manually afterwards. I'm planning on adding some convenience functions to make that a one step operation down the road, but don't have them in place yet.

**Comment by avdwerff** [comment]
Ok will try that.
