### ISSUE TITLE
Routing Multiple Displayed Paths

### ISSUE THREAD

**Issue by mjarvis** [ReSwift/ReSwift-Router#27]
This is more of a prompt to discussion, and possibly something to document for users, as this is likely a very common use case.

How would one propose this router could work if the application has multiple displayed paths? (IE a split-screen application, master/detail, sidebar controller with some internal navigation?)

I see two possibilities (I'm sure there are many more) -- One which may work within the current codebase, and one which would require refactoring.

### Multiple `navigationState`
I've noticed that `protocol HasNavigationState` isn't actually used anywhere, so perhaps the naming of the navigation state is less relevant? Could one have multiple navigation states? ie `masterState` and `detailState`, Building a tree of some kind when a given route/controller has two visible children?
I could see extending `SetRouteAction` such that there is a `SetMasterRouteAction` and `SetDetailRouteAction` etc when it splits.

This seems like it could be done within the current codebase -- I'll have to test it and see

```swift
struct State: StateType {
    var rootState: NavigationState
    var masterState: NavigationState
    var detailState: NavigationState
}

store.dispatch(SetRootRouteAction([masterDetailContainerRoute]))
store.dispatch(SetMasterRouteAction([documentRoute]))
store.dispatch(SetDetailRouteAction([marginEditorRoute]))
```

we'd then have three routers involved, one for each `NavigationState`, and the AppReducer would pass the correct navigationState to `NavigationReducer.handleAction` depending on the action.

### Route as Tree instead of Array
Alternatively, one could represent the current route as a recursive tree instead of an array:
```swift
indirect enum Route {
    case Node(RouteElementIdentifier, [Route])
}
```
While this would be more much work to write out and understand initially, it maintains a single navigationState. An example single navigation structure could look like
```swift
SetRouteAction(.Node(firstRoute, [
    .Node(secondRoute, [
        .Node(thirdRoute, [])
        ])
    ]))
```
and a nested master/detail would be the following:
```swift
SetRouteAction(.Node(mainRoute, [
    .Node(masterRoute, [
        .Node(documentRoute, [])
        ]),
    .Node(detailRoute, [
        .Node(marginEditorRoute, [])
        ]),
    ]))
```
Another downside to this choice is it provides no compile time hinting as to how many children can exist, whereas the first option its immediately obvious, because there are X navigation states. (However, the current implementation provides no compile time hinting as to what routes exist, nor how they can be mixed together, only runtime errors)

**Comment by Ben-G** [comment]
@mjarvis sorry for the late response on this. I've been traveling and missed following up on opened issue s afterwards.

The idea of multiple routers is interesting and definitely something that should be supported. We've moved away from the `HasNavigationState` protocol in part to enable having multiple routers.

The solution you suggested, with having multiple routing entries in the app state should work with the current release of ReSwift-Router. You would need to create two routers and pass them the two different state slices. Then you'd need to set up different actions.

The only trick is that you'd need to create a second `NavigationReducer` manually (https://github.com/ReSwift/ReSwift-Router/blob/master/ReSwiftRouter/NavigationReducer.swift) that listens to your actions that are specific for the second route (we could make this easier by making the `NavigationReducer` generic over the action types it cares about in future).

Hope this are some useful pointers & I hope they don't come much too late!

I'll leave this issue open as I'd like us to implement & document a solution for routing with multiple paths.

**Comment by mjarvis** [comment]
@Ben-G Not too late -- thanks for the response 👍
