### ISSUE TITLE
Fail to support swift3 or xcode8

### ISSUE THREAD

**Issue by madhu-b** [ReSwift/ReSwift-Router#38]
Hi 

I updated to xcode8 and Swift3 . We use 
	pod 'ReSwift'
	pod 'ReSwiftRouter'
When we want to implement StoreSubscriber in our ViewController. It started giving weird errors.

i have uploaded some errors i'm getting. Please give me syntax for subscribing to store and unsubscribing in swift3 

My Code:
 store.subscribe(self) { state in
            (state.momentState, state.feedState)
        }

 store.unsubscribe(self)

var store = Store<State>(reducer: AppReducer() as AnyReducer, state: nil, middleware: [loggingMiddleware])

![error2](https://cloud.githubusercontent.com/assets/8953930/18905390/8abc9d50-8580-11e6-848e-c29058d25c68.png)
![error1](https://cloud.githubusercontent.com/assets/8953930/18905392/8b581186-8580-11e6-93c0-b93a4566a225.png)

@Ben-G  @askielboe  @agentk  @garnett

**Comment by Ben-G** [comment]
@madhu-b Would you mind checking the Swift 3 branch of the GitHub Browser Example?
https://github.com/ReSwift/GitHubBrowserExample/tree/swift-3

It uses ReSwift and ReSwiftRouter's swift 3 version.

Explicitly defining the `StoreSubscriberState` should not be necessary if you have implemented the `newState` method in the ViewController.

Hope this hints help!

**Comment by Ben-G** [comment]
Looks like the suggestion fixed the issue. Closing.

**Comment by madhu-b** [comment]
Thanks
