### ISSUE TITLE
Usage with deep-linking and animations

### ISSUE THREAD

**Issue by jschmid** [ReSwift/ReSwift-Router#4]
We are currently looking for a way to better handle our view controllers history, and Swift Flow Router happens to be a nice way to do it. As it's in early development, I'd like to give my 2 cents about one thing that seems to be important.

When re-working the way we handle our view controllers history/state, we also want to add support for deep linking, or what Apple calls [universal links](https://developer.apple.com/library/ios/documentation/General/Conceptual/AppSearch/UniversalLinks.html).

Recreating a `NavigationState` from a URL in `application(_:continueUserActivity:restorationHandler:)` can be easily done. This is tightly related to #3. 

However, implementing `Routable` becomes harder. If your view controllers present many children view controllers with animations (presenting a modal, pushing a controller in `UINavigationController`, ...) and you want to recreate the whole UI, it will take a few seconds and the user will see each view controller being presented one after the other. 

Also, if you are in the state:

> A -> B -> C

And going to 

> A -> B

You will want to have an animation. However if you go to

> A -> D

You will certainly not want the animation from C to B **then** from B to A **then** from A to D.

The implementation in `Routable` should be able to know if the pushed/poped child view controller should be animated or not. 

Any thought on that?

**Comment by Ben-G** [comment]
@jschmid Yes! :100:. The desired `animated` state should be passed into the `Routable`! 
This is simply an artifact of the early development stage :smile: 

Would you consider using this Router for a non Swift Flow project? If so, I would prioritize my plans of distributing the router separately from the core framework, as it currently barely relies on any of its functionality.

Thanks for the input :+1:

**Comment by jschmid** [comment]
We currently use MVVM everywhere in the app and are (somewhat) happy with it. There is no real need to us to use Swift Flow. 

We will monitor closely the next steps or Swift Flow Router :+1:
