### ISSUE TITLE
Release ReSwift Router

### ISSUE THREAD

**Issue by avdwerff** [ReSwift/ReSwift-Router#43]
For a new project I decided to use ReSwift, so I was wondering if the ReSwiftRouter lib has any changes of importance on the roadmap before it will get a release tag in Git (for Swift 3 support)..?
And if not recommended, what is a good alternative navigation architecture with ReSwift?

**Comment by Ben-G** [comment]
Hey @avdwerff. Release 0.4.0 has Swift 3 support. Should be good to use with latest ReSwift release. No immediate changes planned, though there's certainly a backlog of smaller issues I'd like to fix.

Hope that answers your question?

**Comment by avdwerff** [comment]
Yes, thanks! ...is there any public place for backlog items?

**Comment by Ben-G** [comment]
@avdwerff Only the open issues on this repo. They capture anything that is planned to be worked on at some time.

I'll close for now; let me know if you have more questions!
