### ISSUE TITLE
Routing actions for a (deep) navigation stack

### ISSUE THREAD

**Issue by rpassis** [ReSwift/ReSwift-Router#45]
Not sure if this is covered elsewhere but I couldn't find it anywhere in the documentation.

Supposed I have a navigation stack of:

`UINavController -> VC1 -> VC2 -> VC3`

From my `VC1` I can dispatch `SetRouteAction(["VC1", "VC2"]...` to push VC2 into the stack and make it current.

What is the correct way to go about pushing VC3? I can dispatch `SetRouteAction(["VC1", "VC2", "VC3"]...)` but this will obviously not scale too well, and it will prevent me from reusing view controllers in different "stack" arrangements.

My ideal solution would be to simply dispatch `SetRouteAction(["VC2", "VC3"]...)` but this triggers a `changeRouteSegment` instead of a `pushRouteSegment`.

Have I missed something obvious?
Many thanks,
Rog

**Comment by egv** [comment]
you can obviously make your route relative, something like this in `VC2`
```
let currentRoute = store.state.navigationState.route
store.dispatch(ReSwiftRouter.SetRouteAction(currentRoute + ["VC3"]))
```

this will add `VC3` on top of the `VC2` regardless of `VC2` position in route stack

**Comment by rpassis** [comment]
Thanks! Seems obvious in hindsight :)
