### ISSUE TITLE
Building the project with carthage update fails

### ISSUE THREAD

**Issue by nikolasburk** [ReSwift/ReSwift-Router#47]
When I am cloning the project and want to build the dependencies using `carthage update`, the call fails with the following info:

```
*** Fetching Quick
*** Fetching Nimble
Failed to check out repository into /Users/nburk/Library/Caches/org.carthage.CarthageKit/dependencies/Quick: No object named "swift-3.0" exists
```

I also opened an [issue in the carthage repo](https://github.com/Carthage/Carthage/issues/1610), as I'm not sure if that's an issue with carthage or this repository. Does anyone else have the same problem when running `carthage update`?

**Comment by ikesyo** [comment]
See https://github.com/Carthage/Carthage/issues/1610#issuecomment-262428211.

**Comment by ikesyo** [comment]
@nikolasburk I think you should also check #44.

**Comment by juegas** [comment]
@nikolasburk 👍  https://github.com/ReSwift/ReSwift-Router/pull/44 please be sure to comment on that PR to confirm it worked, so we can get it merged!

**Comment by nikolasburk** [comment]
thanks for your responses! as pointed out [here](https://github.com/Carthage/Carthage/issues/1610#issuecomment-262428211), the issue was indeed the fact that the `Cartfile.private` pointed to `github "Quick/Quick" "swift-3.0"` rather than `github "Quick/Quick"`. the PR should be ok to be merged on that side!
