### ISSUE TITLE
Multiple routes with same identifier question

### ISSUE THREAD

**Issue by mattdelves** [ReSwift/ReSwift-Router#55]
I'm in the process of setting up ReSwiftRouter in an app and am running into a problem with some of the routes when popping them off and making sure that the completion handler is appropriately called.

So I start on the route` [Foo, Bar]` and from there I want to go to the route `[Foo, Bar, Bar]`. The push to the second Bar view controller is fine though I'm running into problems when I pop off the Bar route.

In the BarRouter I've setup push and pop functions with the code required, and by placing in breakpoints I can see that the push function is called for BarRouter though the pop function isn't.

This unfortunately results in a weird state whereby the completion handlers aren't called.

Any help in addressing this would be greatly appreciated.

**Comment by Ben-G** [comment]
@mattdelves Short Q to narrow this down: how did you verify that the route is updated from `[Foo, Bar, Bar]` to `[Foo, Bar]`? Are you calling `setRoute` directly?

**Comment by mattdelves** [comment]
So I see this by inserting some breakpoints and then inspecting the navigationState. As for how the route is being set, I'm using the `SetRouteAction` to accomplish that.

**Comment by mattdelves** [comment]
Okay, so this was completely a PEBKAC on my behalf. In the implementation of Routable we had a guard statement that was leaving early and tripping us up. Going to close the issue as everything now works as expected.
