### ISSUE TITLE
SetRouteAction 'route' is inaccessible due to 'internal' protection level in tests

### ISSUE THREAD

**Issue by leungandrew** [ReSwift/ReSwift-Router#56]
I'm trying to write some tests where I check that that my ActionCreator has successfully created and dispatched a SetRouteAction on my dispatcher.

I'd like to be able to read the route that was passed in to the SetRouteAction, however I'm unable to read it.  It would be nice if the SetRouteAction had a public getter on the route (and perhaps even the animated member).

**Comment by hlineholm-flir** [comment]
Why not set the properties of the SetRouteAction to `private(set)`?

**Comment by Ben-G** [comment]
Sorry, there's been a lot going on across the various repos and this issue dropped under my radar. @leungandrew would it be possible to test by inspecting the app state? Similar to tests in ReSwift itself? https://github.com/ReSwift/ReSwift/blob/4.0.0/ReSwiftTests/StoreDispatchTests.swift

Let me know if that doesn't work for you and I'm happy to reopen.
