### ISSUE TITLE
How to use the Router with navigationcontrollers

### ISSUE THREAD

**Issue by avdwerff** [ReSwift/ReSwift-Router#6]
Somehow it confuses me how to setup a router with navigationcontrollers involved. For example, when the first viewcontroller is a navigationcontroller defined in some storyboard, the root viewcontroller for that navigation controller is actually a route segment deeper… so does that mean it would be better not to use the segue connection between the navigationcontroller and its root viewcontroller? For the app I try to add ReSwift, I have multiple storyboard flows with navigationcontrollers.

**Comment by Ben-G** [comment]
@avdwerff Am I understanding you correctly, you are using a single NavigationController?

If so, the first `Routable` would be responsible for presenting that navigation controller. You could hook that up to a route that would be called `"root"`.

Then you would have another `Routable` that maintains the root view controller of the navigation controller. If your first VC in the navigation controller would be displaying a home screen, you could call that route segment `"home"`.

As soon as your app starts you would navigate to `"root","home"`, which would present the the navigation controller and it's default root view controller.

From here on, each pushed view controller would be responsible for a new route segment.

Does this somehow answer your question? Or am I missing something?

Lastly:
> Somehow it confuses me how to setup a router with navigationcontrollers involved. For example, when the first viewcontroller is a navigationcontroller defined in some storyboard, the root viewcontroller for that navigation controller is actually a route segment deeper

It's important to note, that you should deactivate the automatic loading of the main storyboard in your applications info.plist. It's easiest to use the router if your code performs all presentations itself.

**Comment by avdwerff** [comment]
@Ben-G Yes thanks, that answered the question, thanks!

**Comment by avdwerff** [comment]
I noticed that taking your advice that for example navigating to "root","home" (so a navigation controller with some rootviewcontroller) it first gives quickly a black screen (a navigationcontroller with no child) and it is even better noticed when modally presenting a navigationcontroller with some rootviewcontroller (so another 2 segments deeper). Would it not be better to treat the navcontroller and its root as one segment... ?

**Comment by Ben-G** [comment]
You might be bringing up a good point. I'm on vacation right now, so can't try it out. 

The router would definitely support your approach, it's pretty unopponionated. 

I would suggest you try your approach and let me know how it works out :)

**Comment by avdwerff** [comment]
I will do that :).

**Comment by avdwerff** [comment]
So a little further with using ReSwift + Router I face another design problem. What is a good strategy in a navigation stack scenario when having the following: Each view controller corresponds to a multiple choice question and when answered an Answer question action is dispatched which is handled by a reducer and so forwards a new state to the current viewcontroller on the nav stack. On which the viewcontroller will enable a next button. 
So the question is; should the next button just dispatch a new route and after that send for example a Next question action and so the new viewcontroller pushed on top of that will fill out the right question data? In web apps the question index would just be number in the endpoint of the path... any thoughts about this?

**Comment by Ben-G** [comment]
@avdwerff I'm planning on adding better support for router arguments (is discussed in #3). 

For your case it however sounds like your solution is good. One action to change the route, another action for pushing the `nextQuestion`. I would probably maintain a collection of questions in the state, along with a question index. That allows you to provide a `currentQuestion` as part of the state, that can be used by your topmost VC.

Does that make sense? I assume the app is not open source, is it? (would be curious to see it :) )

**Comment by avdwerff** [comment]
Hi yes, I do maintain an index and a currentQuestion, the only thing what made me think was that at one moment the currentQuestion does not reflect the current index... that is, the change route is after next question. It is not opensource but I could for sure send it over to you, it is in its early stage though. Shall I email/slack it?

**Comment by Ben-G** [comment]
@avdwerff I think we talked about this on Slack, but yes, would love to see your project!

**Comment by Ben-G** [comment]
Do you think the ability to have custom data associated with routes from #18 will help you with this?

**Comment by Ben-G** [comment]
Seems like this issue went stale. In case anything new comes up we can reopen.
