### ISSUE TITLE
Why does popRouteSegment(_,_,_) is called on presentING routable, not presentED?

### ISSUE THREAD

**Issue by nikans** [ReSwift/ReSwift-Router#61]
I've presented modally `vc2` on `vc1` from `vc1` like this: `SetRouteAction(["VC1id", "VC2id"])`. On `vc1 routable` `pushRouteSegment(_,_,_)` is being called correctly. 
Then,  when I call `SetRouteAction(["VC1id"])` the `popRouteSegment(_,_,_)` is being called on `vc1 routable`, keeping me from calling `vc2.dismiss(_,_)` because I don't have link to `vc2` there. 
What do I do incorrectly, or is it an expected behaviour?

**Comment by nikans** [comment]
I put together a PR and would like to discuss it further :)

**Comment by Ben-G** [comment]
Hi @nikans, this is indeed expected behavior. The previous `Routable` on the stack should always be responsible for presenting/dismissing the next `Routable`. I'm assuming `vc1` is presenting `vc2`? So you should be able to dismiss `vc2` from `vc1`?

**Comment by nikans** [comment]
Well, you mostly dismiss vc from that very vc, not from the previous one in the stack. Can't see how is it even manageable.
