### ISSUE TITLE
subscribe signature doesn't match

### ISSUE THREAD

**Issue by iksnae** [ReSwift/ReSwift-Router#64]
in Router.swift the store's invoked with self and a selector argument.. this isn't declared in Store. is this a specific branch or something? thank you.
![screen shot 2017-04-11 at 8 49 15 pm](https://cloud.githubusercontent.com/assets/799271/24940527/79816342-1ef8-11e7-9dad-d606479c1e52.png)

**Comment by Ben-G** [comment]
Sorry @iksnae, I seem to have missed this issue while traveling! This should be addressed with the changes in #66.

**Comment by Ben-G** [comment]
Hm I just tried to reproduce this, @iksnae but wasn't able to (by installing Router via carthage for development as discussed in README). Could you provide some more details on how you set up this project?

**Comment by rpassis** [comment]
Hey @Ben-G you can reproduce this by adding the router to a project that already depends on ReSwift4.x i.e.

````
github "ReSwift/ReSwift" ~> 4.0.0
github "ReSwift/ReSwiftRouter"
````

**Comment by DivineDominion** [comment]
Closing b/c super outdated
