### ISSUE TITLE
import ReSwiftRouter requires deployment target iOS 9.1

### ISSUE THREAD

**Issue by waveyus** [ReSwift/ReSwift-Router#7]
when use import ReSwiftRouter, it gives error

Module file's minimum deployment target is ios9.1 v9.1: 

Carthage/Build/iOS/ReSwiftRouter.framework/Modules/ReSwiftRouter.swiftmodule/i386.swiftmodule

Is there anyway to lower it to iOS 8 or make deployment target insensitive? 

Thanks

**Comment by Ben-G** [comment]
@waveyus It should definitely be lowered to 8.0. I will take care of this. This was just a result of a default setting that was never changed. Will change main library to 8.0 as well. Should be able to ship an update tonight.
