### ISSUE TITLE
can we have a simple sample implementaion of ReSwift Router

### ISSUE THREAD

**Issue by ledikari** [ReSwift/ReSwift-Router#75]
this please.

**Comment by Ben-G** [comment]
@ledikari Would you mind providing more details about this issue?

**Comment by Ben-G** [comment]
Will close for now! Feel free to re-open with more details!

**Comment by ledikari** [comment]
A simple working example using Reswift-router.

i mean Reswift has a a sample app you can run to see how it works,

**Comment by trentguillory** [comment]
I too would like this. The examples I've found on the `ReSwift` readme are very small and simple. It would be wonderful to have an example app that shows how to appropriately use `ReSwift-Router` in conjunction with `UINavigationController`, `UITabBarController`, and similar use-cases that involve pushing, popping, and changing route segments.

I was planning to make one myself, but I am now running into issues with my own implementation.
