### ISSUE TITLE
StandardActionConvertible

### ISSUE THREAD

**Issue by wess** [ReSwift/ReSwift-Router#78]
`Use of undeclared type 'StandardActionConvertible'` in NavigationAction.swift

- Xcode: 8.3.3
- Swift 3.1
- iOS 10

**Comment by hlineholm** [comment]
It exists in [ReSwift-Recorder/ReSwiftRecorder/StandardAction.swift](https://github.com/ReSwift/ReSwift-Recorder/blob/c558b9423df15754ba69a6c297510e4f39541ebd/ReSwiftRecorder/StandardAction.swift)
