### ISSUE TITLE
dispatch_release not called on semaphore.

### ISSUE THREAD

**Issue by dtartaglia** [ReSwift/ReSwift-Router#8]
I noticed that dispatch_release is never called on the semaphore. According to Apple's docs: 

> When your application no longer needs the semaphore, it should call dispatch_release to release its reference to the semaphore object and ultimately free its memory."

I would put it in myself with a pull request, but I'm not entirely sure where it should go.

**Comment by Ben-G** [comment]
Very nice catch! I think it should go directly after `dispatch_semaphore_wait`. Beyond that point the semaphore is no longer needed.

**Comment by Ben-G** [comment]
Ah, I might have intuitively remembered this, or just been lucky, but GCD participates in ARC which means we don't need to manually release semaphores, queues, etc.:

> When you build your app using the Objective-C compiler, all dispatch objects are Objective-C objects. As such, when automatic reference counting (ARC) is enabled, dispatch objects are retained and released automatically just like any other Objective-C object. When ARC is not enabled, use the dispatch_retain and dispatch_release functions (or Objective-C semantics) to retain and release your dispatch objects. You cannot use the Core Foundation retain/release functions.

But thanks for paying such close attention! :+1:
